{% set version = "1.0.3" %}
{% set program = "abpoa" %}
{% set PROGRAM = "abPOA" %}

package:
  name: abpoa
  version: {{ version }}

source:
  url: https://github.com/yangao07/{{ PROGRAM }}/releases/download/v{{ version }}/{{ PROGRAM }}-v{{ version }}.tar.gz
  sha256: 64c914ea3b0836397f764a3e71d52a3836a1c993519f18d8074d22aedebf54e0

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - zlib

test:
  commands:
    - {{ program }} --version | grep {{ version }}

about:
  home: https://github.com/yangao07/{{ PROGRAM }}
  license: GPL
  license_file: LICENSE
  summary: 'abPOA: fast SIMD-based partial order alignment using adaptive band'
